### ISSUE TITLE
NewApplication Manual is missing application.conf for non-activator section

### ISSUE THREAD

**Issue by wookietreiber** [playframework/play-generated-docs#7]
I just followed the manual for 2.4.4 new application without activator. I followed the steps and hit run, and there is a **configuration error** explaining I have no `application.conf`. This leaves the non-activator new app section more or less incomplete.

**Comment by wookietreiber** [comment]
I just realized that all the other sources you need for an out-of-the-box experience you'll get with activator are also missing. Would you be open to adding the most minimal non-activator setup / files that gives you an error free `run`?

**Comment by gmethvin** [comment]
This repo is for generated docs. You can submit issues/PRs to the playframework repo
